import type { Instructor } from "../@types/instructor";

export const instructors: Instructor[] = [
  {
    name: "John Doe",
    title: "Senior Full-Stack Developer",
    bio: "John has 10+ years of experience building scalable web apps. He has taught over 50,000 students worldwide and specializes in JavaScript, Node.js, and cloud technologies.",
    profile: "https://randomuser.me/api/portraits/men/32.jpg",
    email: "john.doe@example.com",
    phone: "+1 555-123-4567",
    linkedin: "https://linkedin.com/in/johndoe",
    twitter: "https://twitter.com/johndoe",
    website: "https://johndoe.dev",
    students: 50000,
    courses: 12,
    experience: 10,
    rating: 4.8,
  },
  {
    name: "Will Smith",
    title: "Frontend Engineer & React Specialist",
    bio: "Will is a passionate frontend engineer with 8 years of experience in React, Redux, and modern frontend architectures. He focuses on performance optimization and developer productivity.",
    profile: "https://randomuser.me/api/portraits/men/45.jpg",
    email: "will.smith@example.com",
    linkedin: "https://linkedin.com/in/willsmith",
    twitter: "https://twitter.com/willsmithdev",
    students: 32000,
    courses: 8,
    experience: 8,
    rating: 4.7,
  },
  {
    name: "Ajay Rana",
    title: "Python Developer & Data Enthusiast",
    bio: "Ajay has been teaching Python and automation for beginners for 6 years. He believes in hands-on learning and building real-world projects from day one.",
    profile: "https://randomuser.me/api/portraits/men/23.jpg",
    email: "ajay.rana@example.com",
    linkedin: "https://linkedin.com/in/ajayrana",
    website: "https://ajaycodes.com",
    students: 25000,
    courses: 6,
    experience: 6,
    rating: 4.6,
  },
  {
    name: "John Abharam",
    title: "Data Scientist",
    bio: "John is a data scientist with a strong background in machine learning, visualization, and AI. He has worked with Fortune 500 companies and loves teaching data science to beginners.",
    profile: "https://randomuser.me/api/portraits/men/60.jpg",
    email: "john.abh@example.com",
    linkedin: "https://linkedin.com/in/johnabharam",
    twitter: "https://twitter.com/johnabh",
    students: 15000,
    courses: 4,
    experience: 7,
    rating: 4.9,
  },
  {
    name: "Bikky",
    title: "UI/UX Designer",
    bio: "Bikky is a creative designer with 5 years of experience in UX research, wireframing, and Figma prototyping. He has mentored hundreds of aspiring designers to launch their careers.",
    profile: "https://randomuser.me/api/portraits/men/70.jpg",
    email: "bikky.design@example.com",
    linkedin: "https://linkedin.com/in/bikkyux",
    website: "https://bikkyux.com",
    students: 8000,
    courses: 3,
    experience: 5,
    rating: 4.5,
  },
  {
    name: "Alex",
    title: "Backend Engineer",
    bio: "Alex is a backend developer who specializes in Node.js and API development. He has worked on multiple SaaS products and is passionate about clean code and scalable systems.",
    profile: "https://randomuser.me/api/portraits/men/12.jpg",
    email: "alex.dev@example.com",
    linkedin: "https://linkedin.com/in/alexdev",
    students: 12000,
    courses: 5,
    experience: 6,
    rating: 4.7,
  },
];
